# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Sync certificates"
  lane :sync_certificates do
    #read-only disables match from overriding the existing certificates.
    match({readonly: true, type: "appstore"})
  end
  desc "Push beta"
  lane :beta do
   increment_build_number
    build_app
    upload_to_testflight
  end
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "mist-ios.xcodeproj")
    build_app(scheme: "mist-ios")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
